%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sambrooke/Repos/j-tools/north_fork_toutle/fedele_paola2007.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/20 11:21:37

%% Import the data
[~, ~, raw] = xlsread('/Users/sambrooke/Repos/j-tools/north_fork_toutle/fedele_paola2007.xlsx','Sheet1');
raw = raw(5:19,4:5);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
xi2 = data(:,1);
f2 = data(:,2);

%% Clear temporary variables
clearvars data raw R;

%% Import the data
[~, ~, raw] = xlsread('/Users/sambrooke/Repos/j-tools/north_fork_toutle/fedele_paola2007.xlsx','Sheet1');
raw = raw(:,1:2);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
xi = data(:,1);
f = data(:,2);

%% Clear temporary variables
clearvars data raw R;
