function [coord_table] = get_coords(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ID,LAT,LON,ELE,TIME,NAME] = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [ID,LAT,LON,ELE,TIME,NAME] = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [ID,lat,lon,ele,time,name] = get_coords('G10_coords.csv',2, 63);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/01/16 13:30:06

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
%	column6: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ID = dataArray{:, 1};
lat = dataArray{:, 2};
lon = dataArray{:, 3};
ele = dataArray{:, 4};
time = dataArray{:, 5};
name = dataArray{:, 6};

coord_table = table(ID,lat,lon,ele,time,...
    'RowNames',name);


